language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit2.1  # current head of 2.1 branch

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install https://luarocks.org/manifests/olivine-labs/busted-2.0.rc11-0.rockspec
  - luarocks install loadkit
  - luarocks make

script: busted
